# Generated by Django 3.1.2 on 2020-10-29 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nail', '0003_categorypage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorypage',
            name='category',
        ),
        migrations.DeleteModel(
            name='Main',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CategoryPage',
        ),
    ]
