# Generated by Django 3.1.2 on 2020-10-31 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nail', '0004_auto_20201029_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('descriprion', models.CharField(max_length=20, verbose_name='Описание')),
                ('context', models.TextField(max_length=250, verbose_name='Содержание')),
                ('insta', models.CharField(max_length=100, verbose_name='Инстаграм')),
                ('facebook', models.CharField(max_length=100, verbose_name='Фейсбук')),
                ('telegram', models.CharField(max_length=100, verbose_name='Телеграм')),
            ],
            options={
                'verbose_name': 'Главная страница(шапка)',
                'verbose_name_plural': 'Главная страница(шапка)',
            },
        ),
    ]
