# Generated by Django 3.1.2 on 2020-10-31 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nail', '0005_header'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header',
            old_name='descriprion',
            new_name='description',
        ),
    ]
