# Generated by Django 3.1.2 on 2020-10-31 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nail', '0006_auto_20201031_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фейсбук'),
        ),
        migrations.AlterField(
            model_name='header',
            name='insta',
            field=models.CharField(blank=True, max_length=100, verbose_name='Инстаграм'),
        ),
        migrations.AlterField(
            model_name='header',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Телеграм'),
        ),
        migrations.AlterField(
            model_name='header',
            name='title',
            field=models.CharField(blank=True, max_length=20, verbose_name='Название'),
        ),
    ]
