# Generated by Django 3.1.2 on 2020-10-31 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nail', '0007_auto_20201031_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header',
            old_name='context',
            new_name='content',
        ),
    ]
