# Generated by Django 3.1.2 on 2020-11-02 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nail', '0009_reserv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserv',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
