# Generated by Django 3.1.2 on 2020-11-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nail', '0014_auto_20201102_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserv',
            name='time',
            field=models.DateField(blank=True, verbose_name='Запись на число'),
        ),
    ]
