# Generated by Django 3.1.2 on 2020-11-02 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nail', '0017_auto_20201102_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserv',
            name='time',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Запись на число'),
        ),
    ]
