# Generated by Django 3.1.2 on 2020-11-02 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nail', '0018_auto_20201102_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserv',
            name='create_time',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Заявка подана'),
        ),
    ]
