# Generated by Django 3.1.2 on 2020-11-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nail', '0020_auto_20201102_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('content', models.TextField(max_length=5000, verbose_name='Описание')),
                ('picture', models.ImageField(upload_to='images/services', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
