# Generated by Django 3.1.2 on 2020-11-06 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nail', '0022_auto_20201104_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('description', models.TextField(max_length=80, verbose_name='Описание')),
                ('cash', models.CharField(max_length=40, verbose_name='Цена или другое')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nail.services', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Прайс',
                'verbose_name_plural': 'Прайс',
            },
        ),
    ]
