# Generated by Django 3.1.2 on 2020-11-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nail', '0023_pricelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='cash',
            field=models.CharField(blank=True, max_length=40, verbose_name='Цена или другое'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='description',
            field=models.TextField(blank=True, max_length=80, verbose_name='Описание'),
        ),
    ]
