# Generated by Django 3.1.2 on 2020-11-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nail', '0024_auto_20201106_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('content', models.TextField(max_length=5000, verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Страница Запись',
                'verbose_name_plural': 'Страница Запись',
            },
        ),
    ]
