# Generated by Django 3.1.2 on 2020-11-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nail', '0025_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='url',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
