# Generated by Django 3.1.2 on 2020-11-08 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nail', '0026_booking_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Pages',
        ),
    ]
