# Generated by Django 3.1.2 on 2020-11-10 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nail', '0028_auto_20201110_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='code',
        ),
    ]
